eureka:
  client:
    serviceUrl:
      defaultZone: http://product-eureka.idata365.com/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  datasource:
    app:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:6633/sjBssV2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: haochezu
      password: Sj2018520v2!
#连接池的配置信息
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
      
    statistics:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:6633/sjStatistics?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: haochezu
      password: Sj2018520v2!
#连接池的配置信息   
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000     
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**.xml
  type-aliases-package: com.idata365.entity
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    shop:
      path: /shop/**
      serviceId: service-shop-chezu
    asset:
      path: /asset/**
      serviceId: service-asset-chezu
    account:
      path: /account/**
      serviceId: service-account-chezu
    im:
      path: /im/**
      serviceId: service-im-chezu
    other:
      path: /app/**
      serviceId: service-app-chezu
      
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true     
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000



